//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace second_api_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_TBL
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PermitionTypeID { get; set; }
        public string PhoneNumber { get; set; }
    }
}
